# services:
#   redis:
#     image: redis:latest
#     ports:
#       - 6379:6379


# for valkey - dropin replacement for redis

services:
  valkey:
    image: valkey/valkey:latest
    ports:
      - 6379:6379